name: Test
on: [push]
jobs:
  test:
    runs-on: windows-latest
    container:
      image: emirdeliz/flutter:latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          submodules: recursive
      - uses: ./.github/actions
      - run: cd example && sh scripts/run-integration-test.sh
