name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-22.04
    container:
      image: fischerscode/flutter
      options: --user root
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions
      - run: cd example && sh scripts/run-integration-test.sh
